// <auto-generated />
using LivrariaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LivrariaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250210195849_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("LivrariaAPI.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoPublicacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Livros");

                    b.HasDiscriminator().HasValue("Livro");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LivrariaAPI.Models.LivroDigital", b =>
                {
                    b.HasBaseType("LivrariaAPI.Models.Livro");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TamanhoArquivo")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("LivroDigital");
                });

            modelBuilder.Entity("LivrariaAPI.Models.LivroFisico", b =>
                {
                    b.HasBaseType("LivrariaAPI.Models.Livro");

                    b.Property<double>("Peso")
                        .HasColumnType("REAL");

                    b.Property<string>("TipoCapa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("LivroFisico");
                });
#pragma warning restore 612, 618
        }
    }
}
